# Generated by Django 3.2.15 on 2022-09-23 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banking_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='customer',
        ),
        migrations.AddField(
            model_name='account',
            name='customer_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='banking_api.customer', verbose_name='customer_id'),
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now=True, verbose_name='date_time')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('receiver_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='receiver', to='banking_api.account')),
                ('sender_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='sender', to='banking_api.account')),
            ],
        ),
    ]
