# Generated by Django 3.2.15 on 2022-09-23 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banking_api', '0003_auto_20220923_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='recipient_id',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='sender_id',
        ),
        migrations.AddField(
            model_name='account',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='banking_api.customer', verbose_name='customer'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='recipient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='recipient', to='banking_api.account'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='sender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='sender', to='banking_api.account'),
        ),
    ]
