# Generated by Django 3.2.15 on 2022-09-23 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banking_api', '0004_auto_20220923_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='sender',
        ),
        migrations.AddField(
            model_name='account',
            name='customer_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='banking_api.customer', verbose_name='customer_id'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='recipient_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='recipient_id', to='banking_api.account'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='sender_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='sender_id', to='banking_api.account'),
        ),
    ]
