# Generated by Django 3.2.15 on 2022-09-23 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banking_api', '0005_auto_20220923_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='recipient_id',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='sender_id',
        ),
        migrations.AddField(
            model_name='transfer',
            name='recipient_account_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='recipient_account_id', to='banking_api.account'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='sender_account_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='sender_account_id', to='banking_api.account'),
        ),
    ]
